config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :rails
  resources :songs
  resources :artists
  resources :billboards
  root 'billboards#index'

  get 'billboards/index'


end

app/models/rail.rb
class Rail < ApplicationRecord
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  before_action :set_rail, only: [:show, :edit, :update, :destroy]

  # GET /rails
  # GET /rails.json
  def index
    @rails = Rail.all
  end

  # GET /rails/1
  # GET /rails/1.json
  def show
  end

  # GET /rails/new
  def new
    @rail = Rail.new
  end

  # GET /rails/1/edit
  def edit
  end

  # POST /rails
  # POST /rails.json
  def create
    @rail = Rail.new(rail_params)

    respond_to do |format|
      if @rail.save
        format.html { redirect_to @rail, notice: 'Rail was successfully created.' }
        format.json { render :show, status: :created, location: @rail }
      else
        format.html { render :new }
        format.json { render json: @rail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails/1
  # PATCH/PUT /rails/1.json
  def update
    respond_to do |format|
      if @rail.update(rail_params)
        format.html { redirect_to @rail, notice: 'Rail was successfully updated.' }
        format.json { render :show, status: :ok, location: @rail }
      else
        format.html { render :edit }
        format.json { render json: @rail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails/1
  # DELETE /rails/1.json
  def destroy
    @rail.destroy
    respond_to do |format|
      format.html { redirect_to rails_url, notice: 'Rail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rail
      @rail = Rail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rail_params
      params.require(:rail).permit(:auth, :proj, :category)
    end
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/views/rails/_form.html.erb
<%= form_with(model: rail, local: true) do |form| %>
  <% if rail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rail.errors.count, "error") %> prohibited this rail from being saved:</h2>

      <ul>
      <% rail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :auth %>
    <%= form.text_field :auth %>
  </div>

  <div class="field">
    <%= form.label :proj %>
    <%= form.text_field :proj %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rails/edit.html.erb
<h1>Editing Rail</h1>

<%= render 'form', rail: @rail %>

<%= link_to 'Show', @rail %> |
<%= link_to 'Back', rails_path %>

app/views/rails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rails</h1>

<table>
  <thead>
    <tr>
      <th>Auth</th>
      <th>Proj</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rails.each do |rail| %>
      <tr>
        <td><%= rail.auth %></td>
        <td><%= rail.proj %></td>
        <td><%= rail.category %></td>
        <td><%= link_to 'Show', rail %></td>
        <td><%= link_to 'Edit', edit_rail_path(rail) %></td>
        <td><%= link_to 'Destroy', rail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rail', new_rail_path %>

app/views/rails/new.html.erb
<h1>New Rail</h1>

<%= render 'form', rail: @rail %>

<%= link_to 'Back', rails_path %>

app/views/rails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auth:</strong>
  <%= @rail.auth %>
</p>

<p>
  <strong>Proj:</strong>
  <%= @rail.proj %>
</p>

<p>
  <strong>Category:</strong>
  <%= @rail.category %>
</p>

<%= link_to 'Edit', edit_rail_path(@rail) %> |
<%= link_to 'Back', rails_path %>